prometheus_instances:
  - name: prometheus_1
    base_url: "http://localhost:9090"
    headers: {}
    disable_ssl: false

summary_levels:
  node:
    - kube_node_status_condition
    - kube_node_status_capacity_memory_bytes 
  pod:
    - kube_pod_container_status_restarts_total
  container:
    - container_cpu_usage_seconds_total